### ISSUE TITLE
Let users know that doujins had been filtered

### ISSUE THREAD

**Issue by Kadantte** [chiyadev/nhitomi#4]
When Hitomi doesn't find a Doujin she says No such doujin!
But how about if the tag of that Doujin is banned?
How about adding something like that: 
```
lolicon and shotacon banned by Discord, Please see Discord TOS for more information!
https://discordapp.com/guidelines
```
#Let's_make_this_Bot_better.

**Comment by phosphene47** [comment]
Issue is no longer relevant as we don't automatically filter doujins anymore.
